# Generated by Django 3.1.4 on 2021-10-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='facility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'facility',
            },
        ),
        migrations.CreateModel(
            name='pgdetails',
            fields=[
                ('pg_id', models.AutoField(primary_key=True, serialize=False)),
                ('pg_name', models.CharField(max_length=50)),
                ('pg_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('img', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.area')),
            ],
            options={
                'db_table': 'pgdetails',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
                ('is_admin', models.IntegerField()),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField(null=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.area')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.pgdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.user')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
        migrations.CreateModel(
            name='pgowner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField(null=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.area')),
            ],
            options={
                'db_table': 'pgowner',
            },
        ),
        migrations.CreateModel(
            name='pgfacility',
            fields=[
                ('pg_facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.facility')),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.pgdetails')),
            ],
            options={
                'db_table': 'pgfacility',
            },
        ),
        migrations.AddField(
            model_name='pgdetails',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.pgowner'),
        ),
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('inquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('inquiry_title', models.CharField(max_length=20)),
                ('inquiry_type', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.user')),
            ],
            options={
                'db_table': 'inquiry',
            },
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('gallery_name', models.CharField(max_length=50)),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.pgdetails')),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('rate', models.IntegerField(verbose_name=5)),
                ('des', models.CharField(max_length=50)),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.pgdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.user')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='bookingdetails',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField(max_length=20)),
                ('booking_status', models.CharField(max_length=20)),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.pgdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.user')),
            ],
            options={
                'db_table': 'bookingdetails',
            },
        ),
    ]
