# Generated by Django 4.2.6 on 2023-10-26 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_pgtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pgtype',
        ),
    ]
