# Generated by Django 4.2.6 on 2023-10-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_delete_pgtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='pgtype',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
