# Generated by Django 4.2.6 on 2023-10-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_pgdetails_pgtype_alter_pgdetails_pg_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgtype',
            old_name='area_id',
            new_name='pg_id',
        ),
    ]
