# Generated by Django 4.2.6 on 2023-10-26 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_rename_area_id_pgtype_pg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgdetails',
            name='pgtype',
        ),
        migrations.DeleteModel(
            name='pgtype',
        ),
    ]
