# Generated by Django 4.2.6 on 2023-12-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_pgdetails_pgtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
