# Generated by Django 4.2.6 on 2023-12-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_weekmenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeekMenu',
        ),
    ]
